/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as StandardSdsSummaryRouteImport } from './routes/standard-sds-summary'
import { Route as HypothesisMutationRouteImport } from './routes/hypothesis-mutation'
import { Route as FutureWorkRouteImport } from './routes/future-work'
import { Route as DdsmRouteImport } from './routes/ddsm'
import { Route as ContextFreeSensitiveRouteImport } from './routes/context-free-sensitive'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardSdsSummaryRoute = StandardSdsSummaryRouteImport.update({
  id: '/standard-sds-summary',
  path: '/standard-sds-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const HypothesisMutationRoute = HypothesisMutationRouteImport.update({
  id: '/hypothesis-mutation',
  path: '/hypothesis-mutation',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureWorkRoute = FutureWorkRouteImport.update({
  id: '/future-work',
  path: '/future-work',
  getParentRoute: () => rootRouteImport,
} as any)
const DdsmRoute = DdsmRouteImport.update({
  id: '/ddsm',
  path: '/ddsm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextFreeSensitiveRoute = ContextFreeSensitiveRouteImport.update({
  id: '/context-free-sensitive',
  path: '/context-free-sensitive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/context-free-sensitive': typeof ContextFreeSensitiveRoute
  '/ddsm': typeof DdsmRoute
  '/future-work': typeof FutureWorkRoute
  '/hypothesis-mutation': typeof HypothesisMutationRoute
  '/standard-sds-summary': typeof StandardSdsSummaryRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context-free-sensitive': typeof ContextFreeSensitiveRoute
  '/ddsm': typeof DdsmRoute
  '/future-work': typeof FutureWorkRoute
  '/hypothesis-mutation': typeof HypothesisMutationRoute
  '/standard-sds-summary': typeof StandardSdsSummaryRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/context-free-sensitive': typeof ContextFreeSensitiveRoute
  '/ddsm': typeof DdsmRoute
  '/future-work': typeof FutureWorkRoute
  '/hypothesis-mutation': typeof HypothesisMutationRoute
  '/standard-sds-summary': typeof StandardSdsSummaryRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/context-free-sensitive'
    | '/ddsm'
    | '/future-work'
    | '/hypothesis-mutation'
    | '/standard-sds-summary'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/context-free-sensitive'
    | '/ddsm'
    | '/future-work'
    | '/hypothesis-mutation'
    | '/standard-sds-summary'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/context-free-sensitive'
    | '/ddsm'
    | '/future-work'
    | '/hypothesis-mutation'
    | '/standard-sds-summary'
    | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextFreeSensitiveRoute: typeof ContextFreeSensitiveRoute
  DdsmRoute: typeof DdsmRoute
  FutureWorkRoute: typeof FutureWorkRoute
  HypothesisMutationRoute: typeof HypothesisMutationRoute
  StandardSdsSummaryRoute: typeof StandardSdsSummaryRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard-sds-summary': {
      id: '/standard-sds-summary'
      path: '/standard-sds-summary'
      fullPath: '/standard-sds-summary'
      preLoaderRoute: typeof StandardSdsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hypothesis-mutation': {
      id: '/hypothesis-mutation'
      path: '/hypothesis-mutation'
      fullPath: '/hypothesis-mutation'
      preLoaderRoute: typeof HypothesisMutationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-work': {
      id: '/future-work'
      path: '/future-work'
      fullPath: '/future-work'
      preLoaderRoute: typeof FutureWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ddsm': {
      id: '/ddsm'
      path: '/ddsm'
      fullPath: '/ddsm'
      preLoaderRoute: typeof DdsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context-free-sensitive': {
      id: '/context-free-sensitive'
      path: '/context-free-sensitive'
      fullPath: '/context-free-sensitive'
      preLoaderRoute: typeof ContextFreeSensitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextFreeSensitiveRoute: ContextFreeSensitiveRoute,
  DdsmRoute: DdsmRoute,
  FutureWorkRoute: FutureWorkRoute,
  HypothesisMutationRoute: HypothesisMutationRoute,
  StandardSdsSummaryRoute: StandardSdsSummaryRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
