"""Shared symbols and helpers for DDSM-style symbolic derivations.

Every variant script derives some subset of: one-step evolution function,
alpha_min, zeta (robustness), gamma (steady state). This module fixes the
symbol names so results are directly comparable across variants, and writes
results out as a TypeScript module of LaTeX string constants that bean's MDX
files can import directly -- no copy/pasting formulae by hand.
"""

from pathlib import Path

import sympy as sp

alpha, beta, c_i = sp.symbols("alpha beta c_i", positive=True)

GENERATED_DIR = Path(__file__).resolve().parents[2] / "bean" / "markdown" / "generated"


def alpha_min_from_evolution(evolution_expr):
    """Solve d(evolution_expr)/d(c_i) at c_i=0 > 1 for alpha, return the boundary alpha."""
    derivative_at_zero = sp.diff(evolution_expr, c_i).subs(c_i, 0)
    solutions = sp.solve(sp.Eq(derivative_at_zero, 1), alpha)
    if len(solutions) != 1:
        raise ValueError(f"expected exactly one alpha_min solution, got {solutions}")
    return sp.simplify(solutions[0])


def zeta_from_alpha_min(alpha_min_expr):
    """Robustness: proportion of valid (alpha, beta) space (beta < alpha <= 1) where alpha > alpha_min.

    The valid space is the triangle beta < alpha <= 1, area 1/2. The converging
    subspace, for each beta in [0, 1), has width (1 - alpha_min(beta)). zeta is
    that converging area divided by the valid triangle's area.

    Sanity check: for standard SDS, alpha_min = 1/(2-beta) gives zeta = 2(1-ln 2),
    matching thesis eq. 3.7.
    """
    converging_area = sp.sympify(sp.integrate(1 - alpha_min_expr, (beta, 0, 1)))
    valid_triangle_area = sp.Rational(1, 2)
    return sp.simplify(converging_area / valid_triangle_area)


def write_ts(filename: str, values: dict[str, str]) -> Path:
    """Write {name: latex_string} pairs as exported TS string constants.

    Import from MDX like:
        import { ALPHA_MIN } from "./generated/context_free.ts";
        <InlineMath math={ALPHA_MIN} />
    """
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    out_path = GENERATED_DIR / filename
    lines = [
        "// Auto-generated by analysis/python -- do not edit by hand.",
        "// Regenerate by re-running the corresponding script in analysis/python/variants/.",
        "",
    ]
    for name, latex in values.items():
        escaped = latex.replace("\\", "\\\\")
        lines.append(f'export const {name} = "{escaped}";')
    out_path.write_text("\n".join(lines) + "\n")
    return out_path


def to_latex(expr) -> str:
    return sp.latex(sp.simplify(expr))
